<?php
include '../db/db.php';
include '../db/queries.php';
$firstname = filter_input(INPUT_POST, 'firstname', FILTER_SANITIZE_STRING);
$lastname = filter_input(INPUT_POST, 'lastname', FILTER_SANITIZE_STRING);
$emailadd = filter_input(INPUT_POST, 'emailadd', FILTER_SANITIZE_EMAIL);
$category = filter_input(INPUT_POST, 'category', FILTER_SANITIZE_STRING);
$password = generateCode();
$hashed_password = password_hash($password, PASSWORD_DEFAULT);

if (emailAddressCheck($conn, $emailadd, 'Faculty')) {
  send_message_and_redirect("Email is already in use", "/ereliv/admin/facultyregis.php");
} 

add_faculty($conn, $firstname, $lastname, $emailadd, $hashed_password, $category);

$redirect = "/ereliv/admin/facultyregis.php";
$title = "PUPQCRMS Faculty Account Created!";
$body = "Welcome to the PUPQCRMS Prof. ".$lastname." <br> Admin of the System had created the account for you and here are your credentials:<br>Email: ".$emailadd."<br>Password: ".$password."<br> The password was auto-generated by the system for privacy purposes.";

sendEmail($conn, $emailadd, $title, $body, $redirect);

send_message_and_redirect("Account Successfully Added", $redirect);



