<?php
include_once '../backend/csrfTokenCheck.php';
include '../db/db.php';
include '../db/queries.php';

$response = array();

$firstname = filter_input(INPUT_POST, 'firstname', FILTER_SANITIZE_STRING);
$lastname = filter_input(INPUT_POST, 'lastname', FILTER_SANITIZE_STRING);
$emailadd = filter_input(INPUT_POST, 'emailadd', FILTER_SANITIZE_EMAIL);
$category = filter_input(INPUT_POST, 'category', FILTER_SANITIZE_STRING);
$password = generateCode();
$hashed_password = password_hash($password, PASSWORD_DEFAULT);

if (emailAddressCheck($conn, $emailadd, 'Faculty')) {
  $response['status'] = "error";
  $response['message'] = "Email address has already been used";
  echo json_encode($response);
  exit;
}

$errorCheck = add_faculty($conn, $firstname, $lastname, $emailadd, $hashed_password, $category);

if (!empty($errorCheck)) {
  $response['status'] = "error";
  $response['message'] = $errorCheck;
  echo json_encode($response);
  exit;
}

$title = "PUPQCRMS Faculty Account Created!";
$body = "Welcome to the PUPQCRMS Prof. " . $lastname . " <br> Admin of the System had created the account for you and here are your credentials:<br>Email: " . $emailadd . "<br>Password: " . $password . "<br> The password was auto-generated by the system for privacy purposes.";

$errorCheck = sendEmail($conn, $emailadd, $title, $body);

if (!empty($errorCheck)) {
  $response['status'] = "error";
  $response['message'] = $errorCheck;
  echo json_encode($response);
  exit;
}

// Create Notification
$facultyID = getFacultyID($conn, $emailadd);
$issuerID = $_SESSION["userID"];
$content = "Congratulations we have successfully created your account! We are thrilled to welcome you to the PUPQC Paper Management System - E Reliv. This powerful platform will empower you to manage your papers efficiently, collaborate effectively, and streamline your academic processes. We are excited to have you on board and look forward to witnessing your valuable contributions. Should you have any questions or require assistance, please don't hesitate to reach out. Welcome to the PUPQC community!";
$redirect = "#";

$notificationID = createNotif($conn, $title, $content, $redirect);
$issuerID = 1; // Admin
$recipientID = $facultyID;

createNotificationLink($conn, $recipientID, $issuerID, $notificationID, 'faculty', 'admin');

$response['status'] = "success";
$response['message'] = "Account Successfully Added";
echo json_encode($response);